[tool]
[tool.pdm]

[project]
name = "pdm-sbom"
version = "0.6.0"
description = "Generate Software Bill of Materials from PDM based projects"
authors = [
    {name = "Carsten Igel", email = "cig@bite-that-bit.de"},
]
dependencies = [
    "pdm>=2.3.4",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[project.license-files]
paths = [
    "LICENSE",
]


[project.entry-points.pdm]
pdm-sbom = "pdm_sbom:main"


[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"
